import { useState } from 'react';
import { Select, SelectItem, DatePicker, DatePickerInput, Button, DataTable, TableContainer, Table, TableHead, TableRow, TableHeader, TableBody, TableCell } from '@carbon/react';
import { Download, Launch } from '@carbon/react/icons';
import PageLayout from './PageLayout';
import './PageLayout.css';

const REPORT_TYPES = [
  { value: '',      label: '' },
  { value: 'FSP_STATUS',   label: 'FSP Status Summary' },
  { value: 'FSP_AMEND',    label: 'FSP Amendment Report' },
  { value: 'FSP_WORKFLOW', label: 'Workflow Status Report' },
  { value: 'FSP_DISTRICT', label: 'District Activity Report' },
];

interface ReportRow {
  id: string;
  name: string;
  generatedDate: string;
  generatedBy: string;
  format: string;
}

const MOCK_REPORTS: ReportRow[] = [
  { id: '1', name: 'FSP Status Summary',       generatedDate: '2025-04-01', generatedBy: 'jsmith',  format: 'PDF' },
  { id: '2', name: 'FSP Amendment Report',     generatedDate: '2025-03-15', generatedBy: 'mbrown',  format: 'XLSX' },
  { id: '3', name: 'District Activity Report', generatedDate: '2025-02-28', generatedBy: 'twilliams', format: 'PDF' },
];

const HEADERS = [
  { key: 'name',          header: 'Report Name' },
  { key: 'generatedDate', header: 'Generated Date' },
  { key: 'generatedBy',  header: 'Generated By' },
  { key: 'format',        header: 'Format' },
];

export default function JcrsReportsPage() {
  const [reportType, setReportType] = useState('');
  const [results, setResults]       = useState<ReportRow[] | null>(null);

  return (
    <PageLayout title="JCRS Reports">

      <div className="form-section">
        <div className="form-section__title">Report Parameters</div>
        <div className="search-grid">
          <Select id="reportType" labelText="Report Type" value={reportType} onChange={e => setReportType(e.target.value)}>
            {REPORT_TYPES.map(o => <SelectItem key={o.value} value={o.value} text={o.label} />)}
          </Select>
          <Select id="orgUnit" labelText="Organization Unit">
            <SelectItem value="" text="" />
            <SelectItem value="DPG" text="DPG – Penticton" />
            <SelectItem value="DSE" text="DSE – Skeena" />
            <SelectItem value="DQU" text="DQU – Quesnel" />
          </Select>
          <DatePicker datePickerType="range" dateFormat="Y-m-d">
            <DatePickerInput id="dateFrom" labelText="Date From" placeholder="YYYY-MM-DD" />
            <DatePickerInput id="dateTo"   labelText="Date To"   placeholder="YYYY-MM-DD" />
          </DatePicker>
        </div>
        <div className="form-actions">
          <Button kind="primary" renderIcon={Launch} onClick={() => setResults(MOCK_REPORTS)}>
            Generate Report
          </Button>
        </div>
      </div>

      {results && (
        <div className="form-section">
          <div className="form-section__title">Recent Reports</div>
          <DataTable rows={results} headers={HEADERS}>
            {({ rows, headers, getTableProps, getHeaderProps, getRowProps }) => (
              <TableContainer>
                <Table {...getTableProps()} size="sm">
                  <TableHead>
                    <TableRow>
                      {headers.map(h => <TableHeader {...getHeaderProps({ header: h })} key={h.key}>{h.header}</TableHeader>)}
                      <TableHeader key="actions"></TableHeader>
                    </TableRow>
                  </TableHead>
                  <TableBody>
                    {rows.map(row => (
                      <TableRow {...getRowProps({ row })} key={row.id}>
                        {row.cells.map(cell => <TableCell key={cell.id}>{cell.value}</TableCell>)}
                        <TableCell>
                          <Button kind="ghost" size="sm" renderIcon={Download} iconDescription="Download" hasIconOnly />
                        </TableCell>
                      </TableRow>
                    ))}
                  </TableBody>
                </Table>
              </TableContainer>
            )}
          </DataTable>
        </div>
      )}

      <style>{`.search-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(220px, 1fr)); gap: 1rem 1.5rem; }`}</style>
    </PageLayout>
  );
}
